apiVersion: v1
kind: Service
metadata:
  name: name-service
  namespace: default
spec:
  type: LoadBalancer #set as external service (also load balances)
  selector:
    app: name
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: name-serviceaccount
  labels:
    account: name